version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci'
      include: 'scope'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 20
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'
    groups:
      angular:
        applies-to: 'version-updates'
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@types/express'
          - 'express'
          - 'ng-packagr'
          - 'rxjs'
          - 'zone.js'
          - 'tslib'
        update-types:
          - 'minor'
          - 'patch'
      angular-eslint:
        applies-to: 'version-updates'
        patterns:
          - '@angular-eslint/*'
          - 'angular-eslint'
          - 'eslint'
          - 'eslint-*'
          - 'typescript-eslint'
        update-types:
          - 'minor'
          - 'patch'
      angular-query:
        applies-to: 'version-updates'
        patterns:
          - '@tanstack/angular-query*'
        update-types:
          - 'minor'
          - 'patch'
      typescript:
        applies-to: 'version-updates'
        patterns:
          - 'typescript'
        update-types:
          - 'patch'
      other:
        patterns:
          - '*'
