version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/.github/actions/install-deps'
    target-branch: 'main'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci'
      include: 'scope'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Warsaw'
      day: 'saturday'
      time: '06:00'
    groups:
      angular:
        applies-to: 'version-updates'
        update-types: ['minor', 'patch']
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@types/express'
          - 'express'
          - 'ng-packagr'
          - 'rxjs'
          - 'zone.js'
      angular-eslint:
        applies-to: 'version-updates'
        update-types: ['minor', 'patch']
        patterns:
          - '@angular-eslint/*'
          - 'angular-eslint'
          - 'eslint'
          - 'eslint-*'
          - 'typescript-eslint'
      angular-query:
        applies-to: 'version-updates'
        update-types: ['minor', 'patch']
        patterns:
          - '@tanstack/angular-query*'
    ignore:
      - dependency-name: '@angular/*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@angular-devkit/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ng-packagr'
        update-types: ['version-update:semver-major']
      - dependency-name: '@angular-eslint/*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'angular-eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: '@tanstack/angular-query*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'tslib'
        update-types: ['version-update:semver-major']
