packages:
  - 'apps/demo-e2e'
  - '!libs/**'

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@angular/*'
  - '@angular-devkit/*'
  - '@schematics/*'
  - ng-packagr
