# Security: require packages to be at least 7 days old (in minutes) before installation
minimumReleaseAge: 10080
packages:
  - 'apps/demo-e2e'
  - '!libs/**'

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
