name: Install Dependencies
description: Setup node.js then install dependencies

inputs:
  node-version:
    description: 'Which version of Node.js to install'
    required: false
    default: 'lts/*'
  registry-url:
    description: 'Which package registry url to use'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: Setup Package Manager
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'
        check-latest: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
