name: Install Dependencies
description: Setup node.js then install dependencies

inputs:
  node-version:
    description: 'Which version of Node.js to install'
    required: false
    default: 'lts/*'
  registry-url:
    description: 'Which package registry url to use'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: Setup Package Manager
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'
        check-latest: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
