name: Install Dependencies
description: Setup node.js then install dependencies

inputs:
  registry-url:
    description: 'Which package registry url to use'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: Setup Package Manager
      uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      with:
        cache: true
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.node-version'
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'
        check-latest: true

    - name: Install NPM
      shell: bash
      run: npm install --global npm@latest

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
