name: Install Dependencies
description: Setup node.js then install dependencies

inputs:
  node-version:
    description: 'Which version of Node.js to install'
    required: false
    default: 'lts/*'
  pnpm-version:
    description: 'Which version of PNPM to install'
    required: false
    default: '9.x.x'
  registry-url:
    description: 'Which package registry url to use'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: Setup Package Manager
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'
        check-latest: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
