name: Lint

concurrency:
  group: ${{ github.workflow }}-lint-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Run Code Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Check Format
        run: pnpm prettier --check --ignore-unknown .

      - name: Lint
        run: pnpm ng lint
