name: Pull Request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build_test:
    name: Run build and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint
        run: pnpm exec ng lint

      - name: Build
        run: |
          pnpm exec ng build ngx-signal-store-query --configuration=production
          pnpm exec ng build demo --configuration=production --progress=false --verbose

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artefacts
          path: dist/
          retention-days: 7

  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.2-noble
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        browser: ['chromium', 'firefox', 'webkit']
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Run tests
        env:
          HOME: /root
        working-directory: apps/demo-e2e
        run: pnpm exec playwright test --project=${{ matrix.browser }}

      - name: Upload test report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-${{ matrix.browser }}-report
          path: |
            apps/demo-e2e/playwright-report/
            apps/demo-e2e/test-results/
          retention-days: 7
