name: release-please

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: Why was the workflow triggered manually?
        required: true
        type: string

permissions:
  contents: write
  packages: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Prepare release PR or move on with release when PR was accepted
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/install-deps

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: pnpm ng build ngx-signal-store-query --configuration=production

      - name: Copy extra files
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: |
          cp LICENSE dist/libs/ngx-signal-store-query/LICENSE
          cp README.md dist/libs/ngx-signal-store-query/README.md

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: |
          cd dist/libs/ngx-signal-store-query
          npm stage publish --provenance --access=public

  release-mirror:
    needs: release-please
    if: ${{ needs.release-please.result == 'success' && needs.release-please.outputs.created == 'true' && needs.release-please.outputs.version != '' }}
    uses: ./.github/workflows/release-mirror.yml
    with:
      version: ${{ needs.release-please.outputs.version }}
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
